Vagrant.configure("2") do |config|
  ## Choose your base box
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  
  # Base box configuration
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end    

  ## To connect your guest machines to the network,
  config.vm.network :forwarded_port, host: 4567, guest: 80
  
  ## Synced folders
  config.vm.synced_folder "../", "/var/www/html/SteganographyKit" 

  ## For masterless, mount your salt file root
  config.vm.synced_folder "salt/roots/", "/srv/"

  ## Use all the defaults:
  config.vm.provision :salt do |salt|

    salt.minion_config = "salt/minion"
    salt.run_highstate = true

  end
end
